#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	excluded_files = ['testweapon.cpp', 'b_nav.cpp', 'b_navgen.cpp', 'deadbody.cpp', 'fists.cpp', 'bullet.cpp', 'b_files.cpp']

	source = bld.path.ant_glob('*.cpp *.c', excl=excluded_files)
	source += bld.path.parent.ant_glob('qcommon/*.cpp')

	bld.shlib(target = 'fgamex86',
		source = source,
		defines = 'GAME_DLL FGAME_EXPORTS',
		includes = '. ../ ../fgame ../qcommon',
		idx = 1)

