#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.shlib(target = 'fgamex86',
		source = bld.path.ant_glob('*.cpp *.c'),
		defines = 'GAME_DLL FGAME_EXPORTS',
		includes = '. ../ ../fgame ../qcommon')

