#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld.shlib(target = 'cgamex86',
		source = bld.path.ant_glob('*.cpp *.c') + bld.path.parent.ant_glob('fgame/bg_misc.c fgame/bg_pmove.c'),
		defines = 'CGAME_DLL',
		includes = '. ../ ../fgame ../qcommon')

