#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	excluded_files = ['cg_syscalls.c']

	source = bld.path.ant_glob('*.cpp *.c', excl=excluded_files)
	source += bld.path.parent.ant_glob('qcommon/*.cpp')
	source += ['../fgame/bg_misc.c', '../fgame/bg_pmove.c', '../fgame/q_math.c', '../fgame/q_mathsys.c', '../fgame/q_shared.c']

	bld.shlib(target = 'cgame',
		source = source,
		name = 'cgame',
		defines = 'CGAME_DLL',
		includes = '. ../ ../fgame ../qcommon',
		install_path = 'fakk',
		idx = 0)

